### ISSUE TITLE
Error Load Data before trying to read

### ISSUE THREAD

**Issue by nei** [akeneo/ExcelInitBundle#18]
I am getting this warning message ans after that a fatal error. It does not show much information where is the issue. There is a way to have debug messages to see what is going on during this process?

[2017-01-23 18:24:04] translation.WARNING: Translation not found. {"id":"Warning: XMLReader::read(): Load Data before trying to read","domain":"messages","locale":"en"} []
[2017-01-23 18:24:04] batch.ERROR: Encountered an error executing the step: Warning: XMLReader::read(): Load Data before trying to read [] []

```
Fixtures fixtures_currency_csv has been successfully executed.
[2017-01-23 18:24:04] translation.WARNING: Translation not found. {"id":"Warning: XMLReader::read(): Load Data before trying to read","domain":"messages","locale":"en"}
[2017-01-23 18:24:04] batch.ERROR: Encountered an error executing the step: Warning: XMLReader::read(): Load Data before trying to read
An error occurred during the fixtures execution.
Error #0 in class Symfony\Component\Debug\Exception\ContextErrorException: Warning: XMLReader::read(): Load Data before trying to read
#0 [internal function]: Symfony\Component\Debug\ErrorHandler->handleError(2, 'XMLReader::read...', '/Users/neisanto...', 103, Array)
#1 /akeneo-ee/vendor/box/spout/src/Spout/Reader/Wrapper/XMLReader.php(103): XMLReader->read()
#2 /akeneo-ee/vendor/box/spout/src/Spout/Reader/XLSX/RowIterator.php(138): Box\Spout\Reader\Wrapper\XMLReader->read()
#3 /akeneo-ee/vendor/akeneo/excel-init-bundle/src/Iterator/InitFileIterator.php(82): Box\Spout\Reader\XLSX\RowIterator->next()
```

**Comment by jmleroux** [comment]
hello @nei 

i didn't have this error since a long time. If i remember well, it can happen when trying to read an unknown worksheet. Did you customize the xlsx structure?

**Comment by nei** [comment]
Hi @jmleroux 

That was right. I received the file customised by someone else. I had to copy all the data in chunks to a new file and it seems the error disappeared but it took me about 10 hours to go through the file since it was huge :)

It would be very useful if we could add some information on debug level which would help understand where is the issue.

**Comment by jmleroux** [comment]
Totally agree, i just created #20 to keep it in the backlog.
